implement preliminary functions to call cpe and cve api from NIST
EC528-Fall-2023/Evolution-of-Kubernetes- pull request #8
Opened 2023-10-02 03:17 UTC by JeffC25

2023-10-02 19:50 UTC, ujalil101 requested changes
Besides the comment i put, everything looks good!

2023-10-02 19:50 UTC, ujalil101 commented on vulnerability_checker/src/app.py
> +
I recommend putting a little description, saying what this module is doing

2023-10-03 02:26 UTC, JeffC25 commented on vulnerability_checker/src/app.py
> +
I added some comments to the code.

2023-10-03 02:28 UTC, ujalil101 approved these changes
Much better! I think its all good to merge!

2023-10-03 02:29 UTC, merged